### ISSUE TITLE
Error SRA

### ISSUE THREAD

**Issue by alda30** [eng-tools/liquepy#2]
Hi,

When I try to run the example, I get the error below:

`File "/home/ehsan/liquepy/a.py", line 40, in run_sra
    profile = lq.sra.sm_profile_to_pysra(sp, d_inc=d_inc)
AttributeError: module 'liquepy' has no attribute 'sra'`

Am i missing something?

**Comment by millen1m** [comment]
You will need to include import liquepy.sra at the top of your script, since the sra module does not import by default due it having heavy dependencies and slow loading.
